# EXP_ID: 20180607D01
METHOD_NAME: e2e-frcnn-VGG16-C5-im1.5-rmb128-iter12k
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG16.add_VGG16_conv5_body
  NUM_CLASSES: 7
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 120000
  STEPS: [0, 80000, 120000]
RPN:
  SIZES: (32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.add_VGG16_roi_fc_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  WEIGHTS: /home/all/models/Detectron/ImageNetPretrained/vgg16.pkl
  DATASETS: ('scut_train_10x',)
  SCALES: (864,)
  MAX_SIZE: 1080
  IMS_PER_BATCH: 1
  RPN_BATCH_SIZE_PER_IM: 128
  BATCH_SIZE_PER_IM: 128
TEST:
  DATASETS: ('scut_test_1x',)
  SCALE: 864
  MAX_SIZE: 1080
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: output/scut/S2-e2e-frcnn-VGG16-C5-im1.5-rmb128-iter12k/detectron-output
